### ISSUE TITLE
Scoped translations types not working on v1.2

### ISSUE THREAD

**Issue by ubinatus** [QuiiBz/next-international#328]
**Describe the bug**
Usage of scoped translations for either nested objects or dot-notation, is having types issues for both `getScopedI18n` and `useScopedI18n`.

**To Reproduce**
1. Go to the examples/next-app
2. Head to any page that uses either `getScopedI18n` or `useScopedI18n`
3. Typescript server showing error on calls for scoped tranlsations (e.g. `t('test')` in ` /examples/next-app/app/[locale]/client/page.tsx`)

**Expected behavior**
Seems that the retrieval of scoped translations types is having issues on the latest 1.2 version. I've dig a bit and discovered it's related to the return of the cached locales in both `create-get-scoped-i18n` and `create-use-scoped-i18n` introduced in https://github.com/QuiiBz/next-international/pull/314

**Screenshots**
<img width="700" alt="image" src="https://github.com/QuiiBz/next-international/assets/51177379/8505e67d-30e3-4e02-b8d9-7ed77dd11100">

**About (please complete the following information):**
 - next-international version: v1.2
 - Next.js version: v14.0.4

**Additional context**

**Comment by jalezi** [comment]
I have the same problem but with `getScopedI18n()` and with `I18nProviderClient`.

- next-international version: v1.2
- Next.js version: v14.0.4

![next-international@1 2 0-ts-error_4](https://github.com/QuiiBz/next-international/assets/44704999/d32a847a-fb98-45ab-9348-2602611d7d26)

![next-international@1 2 0-ts-error_3](https://github.com/QuiiBz/next-international/assets/44704999/ebed7b1f-3b5a-4a90-9dba-3a72c00a9b86)

**Comment by QuiiBz** [comment]
Fix released in https://github.com/QuiiBz/next-international/releases/tag/1.2.1, thanks!

**Comment by ubinatus** [comment]
@QuiiBz Seems that the `I18nProviderClient` issue detailed above by @jalezi is not resolved yet. Will be creating a PR so solve it as it might need a similar fix as the original description.

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/next-international/releases/tag/1.2.2, thanks!
